export const assessmentList = async (req, res) => {
    let responseData;
    responseData = {
        
          status: true,
          message: "assessment list",
          assessment_id: "22485",
          client_number: "8928001617",
          last_visited_screen: "assessment/1",
          assessment_status: 0,
          medical_issue: "0",
          data: [
                {
                  name: "Personal Details",
                  status: "2"
                },
                {
                  name: "Nutrition & Lifestyle Analysis",
                  status: "2"
                },
                {
                  name: "24 Hour Diet Recall",
                  status: "1"
                },
                {
                  name: "Food Frequency",
                  status: "2"
                },
                {
                  name: "Upload Photo",
                  status: "2"
                },
                {
                  name: "Medical History",
                  status: "2"
                },
                {
                  name: "Note To Mentor & Khyati",
                  status: "2"
                }
            ]
        
    };
  return res.status(200).json(responseData);
}

export const personalDetails = async (req, res) => {
    let responseData;
    responseData = {
        
          status: true,
          message: "Personal Details",
          assessment_id: "22485",
          form_data: {
                
                  id: "199",
                  asid: "22485",
                  user_id: "13506",
                  name: "Rahil Shaikh",
                  email_id: "8898121797@balancenutrition.in",
                  mobile_no: "8898121797",
                  address: "",
                  country: "",
                  state: "",
                  city: "",
                  birth_date: "",
                  gender: "",
                  caste: "",
                  age: "",
                  asses_photo: "",
                  weight: "",
                  height: "",
                  goal_weight: "",
                  other_goal: "",
                  school_time: "",
                  recess_time: "",
                  school_days: "",
                  martial_status: "",
                  family: "",
                  no_children: "",
                  breast_feed: "",
                  excl_breastfeed: "",
                  age_child1: "",
                  age_child2: "",
                  age_child3: "",
                  ass_attachment: "",
                  is_correct: "0",
                  created: "",
                  edit_right: "0",
                  medi: "",
                  ass_mail: "0000-00-00 00:00:00",
                  change_url: "",
                  age_child4: "",
                  age_child5: "",
                  child_status: "",
                  other_caste: "",
                  breast_feed_freq: "",
                  breast_feed_other_freq: "",
                  breast_feed_food: "",
                  body_type: "",
                  is_pregnant: "",
                  pregnancy_month: "",
                  anniversary_date: "",
                  dummy: "",
                  country_name: "",
                  state_name: "",
                  city_name: "",
                  weight_in_kg: "",
                  weight_in_gm: "0",
                  goal_weight_in_kg: "",
                  goal_weight_in_gm: "0",
                  height_in_feet: "",
                  height_in_inch: "0",
                  goal_weight_start: 40
                
          }
    };
  return res.status(200).json(responseData);
}

export const nutritionLifestyleAnalysis = async (req, res) => {
    let responseData;
    responseData = {
      status: true,
      message: "nutrition and lifestyle data",
      assessment_id: "22485",
      reform_question: 0,
      form_data: [
            {
              id: "182",
              asid: "22485",
              new_asid: "0",
              user_id: "27379",
              current_status: "",
              occupation: "",
              job_type: "",
              job_time: "",
              job_hour: "",
              job_meal: "",
              meal_quantity: "",
              play_time: "",
              tution_time: "",
              act_class: "",
              meal_type: "",
              canteen: "",
              job_travel: "",
              travel_inmonth: "",
              travel_country: "",
              lifestyle: "",
              eating_habit: "",
              fnonveg: "",
              pmeat: "",
              smoke: "",
              smoke_habit: "",
              alcohol: "",
              alco_frequency: "",
              alco_intake: "",
              drink_preference: "",
              water_intake: "",
              pastpro: "",
              diet: "",
              exercise: "",
              fast: "",
              visit_hotel: "",
              cuisine: "",
              whocook_meal: "",
              brunch: "",
              facility: "",
              options: "",
              eater: "",
              hunger: "",
              activity: "",
              child_prefer: "",
              kadha_booster: "",
              food_aversion: "",
              food_preference: "",
              ex: "",
              cardio: "",
              cardio_duration: "",
              cardio_frequency: "",
              cardio_time: "",
              weight_training_frequency: "",
              weight_training_duration: "",
              weight_training_time: "",
              yoga: "",
              yoga_duration: "",
              yoga_frequency: "",
              yoga_time: "",
              arobic: "",
              arobic_duration: "",
              arobic_frequency: "",
              arobic_time: "",
              swim: "",
              swim_duration: "",
              swim_frequency: "",
              swim_time: "",
              walk: "",
              walk_duration: "",
              walk_frequency: "",
              walk_time: "",
              jogging: "",
              jogging_duration: "",
              jogging_frequency: "",
              jogging_time: "",
              other: "",
              other_duration: "",
              other_frequency: "",
              other_time: "",
              no_of_cigarettes: "",
              alco_frequency_other: "",
              do_you_fast: "",
              fast_other: "",
              whocook_meal_any_other: "",
              meals_other: "",
              hunger_2: "",
              job_end_time: "",
              other_smoke_habit: "",
              other_no_of_cigarettes: "",
              canteen_2: "",
              canteen_3: "",
              canteen_4: "",
              other_job_type: "",
              other_occupation: "",
              trademil_frequency: "",
              trademil_frequency_other: "",
              trademil_duration: "",
              trademil_time: "",
              eliptical_frequency: "",
              eliptical_frequency_other: "",
              eliptical_duration: "",
              eliptical_time: "",
              gym_cycle_frequency: "",
              gym_cycle_frequency_other: "",
              gym_cycle_duration: "",
              gym_cycle_time: "",
              cycling_frequency: "",
              cycling_frequency_other: "",
              cycling_duration: "",
              cycling_time: "",
              weight_training: "",
              other_exercise: "",
              dance_frequency: "",
              dance_frequency_other: "",
              dance_duration: "",
              dance_time: "",
              zumba_frequency: "",
              zumba_frequency_other: "",
              zumba_duration: "",
              zumba_time: "",
              skipping_frequency: "",
              skipping_frequency_other: "",
              skipping_duration: "",
              skipping_time: "",
              pilates_frequency: "",
              pilates_frequency_other: "",
              pilates_duration: "",
              pilates_time: "",
              other_workout_name: "",
              other_workout_frequency: "",
              any_other_workout_frequency: "",
              other_workout_duration: "",
              other_workout_time: "",
              visit_hotel_other: "",
              fasting_food: "",
              egg_frequency: "",
              activity_other: "",
              jogging_frequency_other: "",
              swim_frequency_other: "",
              yoga_frequency_other: "",
              walk_frequency_other: "",
              weight_training_frequency_other: "",
              other_cuisine: "",
              cardio_frequency_other: "",
              food_allergy: "",
              fasting_window: "",
              any_other_allergy: "",
              sleep_time: "",
              consumption_of_fruits: "",
              sleep_duration: "",
              other_workout_specification: "",
              gluten_product_allergy: "",
              lactose_product_allergy: "",
              other_milk_product_allergy: "",
              other_wheat_product_allergy: "",
              any_other_meal: "",
              any_other_cuisine: "",
              : "",
              breakfast: "",
              lunch: "",
              dinner: "",
              indian: "",
              chinese: "",
              continental: "",
              lactose: "",
              gluten: "",
              soya: "",
              peanuts: "",
              reform_question: 0
            }
        ]
    }
  return res.status(200).json(responseData);
}